### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by iISAF7** [zerebos/BetterDiscordAddons#796] opened 2024-11-10 11:37 UTC
**Which plugin/theme is this about?**
Role Members and PermissionsViewer

**Describe the Bug**
when i start betterdiscord the PermissionsViewer send me the error
and Role Members it work i can enable and disable it but when i enable the plugin isnt work why it only can disable and enable  ?

**To Reproduce**

**Expected Behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/a662eedd-84e6-4e55-b816-3ccfc22d10a5)
![image](https://github.com/user-attachments/assets/ac62e45a-9d27-46a9-9b23-b41d19550aee)
![image](https://github.com/user-attachments/assets/ed75c3f1-9767-4ae5-bbc9-799c7a180069)

**Discord Version**
Stable

**Additional Context**

**Comment by Arya-Fazel** [comment] 2024-11-10 14:15
Same
![image](https://github.com/user-attachments/assets/b2a7953e-3d6e-4d2b-b445-b0cbdd977138)

**Comment by Leah96xxx** [comment] 2024-11-10 14:55
Looks like this might be a duplicate of #794

**Comment by iISAF7** [comment] 2024-11-11 05:32
> Try one of my versions from here: #794 Should work. Please confirm.

ok now it appears to me that it is working, but when I press enable nothing appears as if it is not working
![image](https://github.com/user-attachments/assets/c08882e0-3b2c-4697-9d3c-9cbaf8e2100f)
![image](https://github.com/user-attachments/assets/d2434d31-3d56-4933-8241-835fcfef2ec2)

**Comment by DaddyBoard** [comment] 2024-11-11 10:26
My updated pull request fixes this, found here; https://github.com/zerebos/BetterDiscordAddons/pull/792

**Comment by iISAF7** [comment] 2024-11-11 11:47
> Yeah, I suggest you try the last version (last post on that issue) , not the first. Should work. Please confirm.

bro do you have discord ?

**Comment by zerebos** [comment] 2024-12-15 06:58
Duplicate of a few others

**Closed by zerebos** 2024-12-15 06:58 UTC
Labels: bug
