### ISSUE TITLE
[Bug] Markdown headers don't have the role color applied to them in Better Role Colors

### ISSUE THREAD

**Issue by Fungustober** [zerebos/BetterDiscordAddons#780] opened 2024-09-17 02:40 UTC
**Which plugin/theme is this about?**
BetterRoleColors.

**Describe the Bug**
Markdown headers have the default text color while BetterRoleColors is active, which looks odd when next to the rest of the message, which has the color of the user's role.

**To Reproduce**
Send a message using the discord markdown headers (# followed by space and then the text you want). Here's an example message using all three markdown headers available in Discord:
```# This is H1
## This is H2
### This is H3
This is normal text
```

**Expected Behavior**
The markdown headers being the same color as the rest of the text

**Screenshots**
<img width="268" alt="Screenshot 2024-09-16 213321" src="https://github.com/user-attachments/assets/d0fa37ff-5dbb-4e33-b363-66cbd47efe39">
<img width="233" alt="Screenshot 2024-09-16 213426" src="https://github.com/user-attachments/assets/37e531f8-0769-44b6-b59f-bab5c3f76f4c">

**Discord Version**
stable 327180 (bd5e7f6) Host 1.0.9163 x64 (52153) Build Override: N/A Windows 10 64-bit (10.0.19045)

**Additional Context**
As far as I can tell, The headers are stored in `<div id="message-content-[a bunch of numbers here]"></div>` and are `<h1></h1>`, `<h2></h2>`, or `<h3></h3>` tags with a span inside the main tag, and then a second span inside the first span tag that holds the text.

**Comment by zerebos** [comment] 2024-09-17 06:11
Duplicate of #738 (also opened by you)

**Closed by zerebos** 2024-09-17 06:11 UTC
Labels: bug

**Comment by Fungustober** [comment] 2024-09-17 22:29
Whoops! It's been nearly a year since I opened that, so I'm not surprised I forgot about it. I am a little surprised that I didn't manage to find it when searching in the issues page for it, but I must have overlooked it on accident.
