### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by iDeparture** [zerebos/BetterDiscordAddons#788] opened 2024-10-06 21:28 UTC
**Which plugin/theme is this about?**

 PermissionsViewer
**Describe the Bug**

can't view permissions 
**To Reproduce**

install the plugin and try to use it
**Expected Behavior**

Righ click a user and see "view permissions" in the context menu
**Screenshots**

**Discord Version**
**Additional Context**
Stable and Canary

**Comment by zerebos** [comment] 2024-12-15 06:59
Duplicate of a number of other issues

**Closed by zerebos** 2024-12-15 06:59 UTC
Labels: bug
